// <auto-generated />
using System;
using InvestmentTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestmentTracker.Infrastructure.Migrations
{
    [DbContext(typeof(InvestmentTrackerDbContext))]
    [Migration("20260503181152_InitialAssetRegistry")]
    partial class InitialAssetRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestmentTracker.Domain.Assets.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f85a8e7-8c6d-4f9f-8f9b-3df9274a0f1a"),
                            Exchange = "NASDAQ",
                            Name = "Apple Inc.",
                            Ticker = "AAPL",
                            Type = "Stock"
                        },
                        new
                        {
                            Id = new Guid("6e8e6a5f-7e53-4cbb-80a5-b5a44c9e2c28"),
                            Exchange = "NASDAQ",
                            Name = "Microsoft Corporation",
                            Ticker = "MSFT",
                            Type = "Stock"
                        },
                        new
                        {
                            Id = new Guid("a1fb97da-62ed-41f6-a5e8-c15b7d2060bf"),
                            Exchange = "NYSEARCA",
                            Name = "Vanguard S&P 500 ETF",
                            Ticker = "VOO",
                            Type = "Etf"
                        },
                        new
                        {
                            Id = new Guid("ab42c1c4-690f-4ce4-927e-ea967dfd69cf"),
                            Exchange = "CRYPTO",
                            Name = "Bitcoin",
                            Ticker = "BTC",
                            Type = "Crypto"
                        },
                        new
                        {
                            Id = new Guid("5c25df89-01e0-47d7-b01e-cc4c69d87f04"),
                            Exchange = "CRYPTO",
                            Name = "Ethereum",
                            Ticker = "ETH",
                            Type = "Crypto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
